version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    ports:
      - 8080:8080