version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432

  server:
    environment: 
      - DB_HOST=db
      - DEV=0
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    ports:
      - 8080:8080